### -*- coding: utf-8 -*-
"""EDA과제.R

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VEugXBqblaltjLIikHAOlD-RCMnbu7f8
"""

install.packages("tidyverse")
library(tidyverse)

ggplot(mpg, mapping = aes(x=displ, y = hwy))+
  geom_point(size = 5)+
  geom_smooth(se=F)

ggplot(mpg, mapping = aes(x=displ, y = hwy))+
  geom_point(size = 5)+
  geom_smooth(mapping = aes(group=drv), se=F)

ggplot(mpg, mapping = aes(x=displ, y = hwy))+
  geom_point(size = 5, mapping = aes(color=drv))+
  geom_smooth(mapping = aes(group=drv), se=F,show.legend=T)

ggplot(mpg, mapping = aes(x=displ, y = hwy))+
  geom_point(size = 5, mapping = aes(color=drv))+
  geom_smooth(se=F,show.legend=T)

ggplot(mpg, mapping = aes(x=displ, y = hwy))+
  geom_point(size = 5, mapping = aes(color=drv))+
  geom_smooth(mapping = aes(linetype =drv),se=F,show.legend=T)

p<-ggplot(mpg, aes(x = displ, y = hwy))
p+geom_point(aes(fill=drv),shape=21,color="white", stroke=4, size=5, show.legend = T)



